const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Behaviors.solid,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Anchor,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Keyboard.Cnds.OnKey
	];
};
self.C3_JsPropNameTable = [
	{ScrollTo: 0},
	{"8Direction": 0},
	{NyanCat: 0},
	{Sprite2: 0},
	{bg: 0},
	{Keyboard: 0},
	{Bullet: 0},
	{TacNayn: 0},
	{Laser: 0},
	{Mouse: 0},
	{Touch: 0},
	{Audio: 0},
	{DeathParticle: 0},
	{Sine: 0},
	{Food: 0},
	{Solid: 0},
	{border: 0},
	{Anchor: 0},
	{Life: 0},
	{Score: 0},
	{Apple: 0},
	{RIP: 0},
	{SpriteFont: 0},
	{TiledBackground: 0},
	{NyanCatStatue: 0},
	{SpriteFont2: 0},
	{PlayNyan: 0},
	{Thing: 0},
	{continuee: 0},
	{tutortext: 0},
	{Sprite: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{tutotrr: 0},
	{back: 0},
	{tacBG: 0},
	{netherBG: 0},
	{NyanShield: 0},
	{shield: 0},
	{Sprite5: 0},
	{buttonLeft: 0},
	{buttonRight: 0},
	{buttonDown: 0},
	{buttonUp: 0},
	{Sprite6: 0},
	{scoreTelly: 0},
	{highscore: 0},
	{Layout: 0},
	{Shield: 0},
	{Level: 0},
	{ToggleButton: 0},
	{Highscore: 0}
];

self.InstanceType = {
	NyanCat: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	bg: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {},
	TacNayn: class extends self.ISpriteInstance {},
	Laser: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	DeathParticle: class extends self.IParticlesInstance {},
	Food: class extends self.ISpriteInstance {},
	border: class extends self.ISpriteInstance {},
	Life: class extends self.ISpriteFontInstance {},
	Score: class extends self.ISpriteFontInstance {},
	Apple: class extends self.ISpriteInstance {},
	RIP: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	NyanCatStatue: class extends self.ISpriteInstance {},
	SpriteFont2: class extends self.ISpriteFontInstance {},
	PlayNyan: class extends self.ISpriteInstance {},
	Thing: class extends self.ISpriteInstance {},
	continuee: class extends self.ISpriteInstance {},
	tutortext: class extends self.ISpriteFontInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	tutotrr: class extends self.ISpriteInstance {},
	back: class extends self.ISpriteInstance {},
	tacBG: class extends self.ITiledBackgroundInstance {},
	netherBG: class extends self.ITiledBackgroundInstance {},
	NyanShield: class extends self.ISpriteInstance {},
	shield: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	buttonLeft: class extends self.ISpriteInstance {},
	buttonRight: class extends self.ISpriteInstance {},
	buttonDown: class extends self.ISpriteInstance {},
	buttonUp: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	scoreTelly: class extends self.ISpriteFontInstance {},
	highscore: class extends self.ISpriteFontInstance {}
}